name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework net50
    - name: Test
      run: dotnet test --no-restore --verbosity normal --framework net50
